version: '3.8'

services:
  api:
    build: api
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: yarn start:dev

  app:
    build:
      context: frontend
    ports:
      - "3001:3001"
      - "6000:6000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: yarn start

  storybook:
    build:
      context: frontend
    ports:
      - "6006:6006"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CI=true
    command: yarn storybook
    depends_on:
      - app
