version: '3.8'

services:
  api:
    build: api
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: yarn start:dev
